# 配置语言及相应版本
language: node_js

node_js:
  - "4.2.6"

before_install:
- openssl aes-256-cbc -K $encrypted_2665ac12bbfc_key -iv $encrypted_2665ac12bbfc_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'zqz'
- git config --global user.email zqz@zhaoqize.com
install:
#- npm install hexo-cli -g
#- npm install
script:
#- npm run deploy

# 项目所在分支
branches:
  only:
  - master
